select
	USR_LMS_USER_ID, USR_FIRST_NAME, USR_LAST_NAME, USER_ACTIVITY, USR_ORGANIZATION_ID,
	PRG_ENTITY_ID, PRG_LMS_USER_ID, PRG_STATUS, PRG_START_DATE, PRG_COMPLETE_DATE, 
	CNTLCL_TITLE, CONTENT_ACTIVITY
from ADHOC_USER
left join (
	select
		PRG_ENTITY_ID, PRG_LMS_USER_ID, PRG_STATUS, PRG_START_DATE, PRG_COMPLETE_DATE, 
		CNTLCL_TITLE, CONTENT_ACTIVITY
	from ADHOC_PROGRESS
	join ADHOC_CONTENT on PRG_ENTITY_ID = CNTLCL_CONTENT_ID
	where PRG_ENTITY_ID = 'F735BCAD63AA4A728892BD04E2FDA219' 
		/*and PRG_STATUS = 'completed'*/
	) as CrsInfo on USR_LMS_USER_ID = PRG_LMS_USER_ID
